version: '3.1'

services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mongo/:/home/shared
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: tests
      MYSQL_USER: gabrielrufino
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql/:/home/shared
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: gabrielrufino
      PMA_PASSWORD: 12345678
    ports:
      - "80"
    depends_on:
      - mysql
  portainer:
    image: portainer/portainer-ce
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: gabrielrufino
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/:/home/shared
  rethinkdb:
    image: rethinkdb:2
    ports:
      - "28015:28015"
      - "28016:8080"
    volumes:
      - ./volumes/rethinkdb/:/home/shared
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
        SA_PASSWORD: "password@123"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  strapi:
    image: strapi/strapi:3
    volumes:
      - ./volumes/strapi:/srv/app
    ports:
      - "1337:1337"
  ubuntu:
    image: ubuntu:20.04
    tty: true
    volumes:
      - ./volumes/ubuntu/:/home/shared
  verdaccio:
    image: verdaccio/verdaccio:4
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./volumes/verdaccio/storage:/verdaccio/storage"
