version: '3.9'

services:
  appsmith:
    image: appsmith/appsmith-ce:v1.6.16
    ports:
      - 8085:80
      - 443:443
      - 9001:9001
    volumes:
      - appsmith:/appsmith-stacks
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    # restart: always
  archlinux:
    image: archlinux
    tty: true
    volumes:
      - ./volumes/archlinux/:/home/shared
    # ports:
    #   - "22002:22"
    # restart: always
  debian:
    image: debian
    tty: true
    volumes:
      - ./volumes/debian/:/home/shared
    # ports:
    #   - "22003:22"
    # restart: always
  fedora:
    image: fedora:35
    tty: true
    volumes:
      - ./volumes/fedora/:/home/shared
    # ports:
    #   - "22004:22"
    # restart: always
  gitea:
    image: gitea/gitea:1
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3002:3000
      - 222:22
    # restart: always
  grafana:
    image: grafana/grafana:8.4.4
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    # restart: always
  kali:
    image: kalilinux/kali-rolling
    tty: true
    # ports:
    #   - "22000:22"
  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    # restart: always
  matomo:
    image: matomo:4
    ports:
      - 8086:80
    environment:
      MATOMO_DATABASE_HOST: mysql
      MATOMO_DATABASE_USERNAME: root
      MATOMO_DATABASE_PASSWORD: password
      MATOMO_DATABASE_DBNAME: matomo_db
    depends_on:
      - mysql
    # restart: always
  mautic:
    image: mautic/mautic
    ports:
      - 8082:80
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: root
      MAUTIC_DB_PASSWORD: password
      MAUTIC_DB_NAME: mautic
      MAUTIC_RUN_CRON_JOBS: 'true'
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
    depends_on:
      - mysql
    # restart: always
  metabase:
    image: metabase/metabase:v0.42.4
    ports:
      - 3001:3000
    environment: 
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase:/metabase-data
    # restart: always
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mongo/:/home/shared
    # restart: always
  mysql:
    image: mysql:8
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql-mode=""
    environment:
      MYSQL_DATABASE: tests
      MYSQL_USER: gabrielrufino
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/:/home/shared
      - mysql:/var/lib/mysql
    # restart: always
  nextcloud:
    image: nextcloud:23.0.3-apache
    ports:
      - 8083:80
    volumes:
      - nextcloud:/var/www/html
    # restart: always
  nginx:
    image: nginx:1
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # restart: always
  openvscode:
    image: gitpod/openvscode-server:1.65.2
    init: true
    tty: true
    ports:
      - 3003:3000
    volumes:
      - ./volumes/openvscode:/home/workspace:cached
    # restart: always
  pgadmin:
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gabrielrufino.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 16543:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    # restart: always
  phpmyadmin:
    image: phpmyadmin:5.1.3
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8087:80
    # restart: always
  portainer:
    image: portainer/portainer-ce:2.11.1
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
    # restart: always
  postgres:
    image: postgres:13
    # [Use the image bellow for postgres with ssl]
    # image: fantix/postgres-ssl:13.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/:/home/shared
      - postgres:/var/lib/postgresql/data
    # restart: always
  prometheus:
    image: prom/prometheus:v2.32.1
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    # restart: always
  promtail:
    image: grafana/promtail:2.3.0
    ports:
      - 9080:9080
    volumes:
      - ./config/promtail/config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml
    # restart: always
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq
      - ./volumes/rabbitmq/log/:/var/log/rabbitmq
    # restart: always
  redis:
    image: redis:6
    ports:
      - 6379:6379
    # restart: always
  redisinsight:
    image: redislabs/redisinsight:1.11.1
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    # restart: always
  rethinkdb:
    image: rethinkdb:2
    ports:
      - 28015:28015
      - 28016:8080
    volumes:
      - ./volumes/rethinkdb/:/home/shared
    # restart: always
  sonic:
    image: valeriansaliou/sonic:v1.3.2
    ports:
      - 1491:1491
    volumes:
      - ./volumes/sonic/sonic.cfg:/etc/sonic.cfg
      - ./volumes/sonic/store/:/var/lib/sonic/store/
    # restart: always
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: password@123
        ACCEPT_EULA: Y
    ports:
      - 1433:1433
    # restart: always
  strapi:
    image: strapi/strapi:3
    volumes:
      - ./volumes/strapi:/srv/app
    ports:
      - 1337:1337
    # restart: always
  ubuntu:
    image: ubuntu:20.04
    tty: true
    volumes:
      - ./volumes/ubuntu/:/home/shared
    # ports:
    #   - "22001:22"
    # restart: always
  verdaccio:
    image: verdaccio/verdaccio:4
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - 4873:4873
    volumes:
      - ./volumes/verdaccio/storage:/verdaccio/storage
    # restart: always

volumes:
  appsmith:
  gitea:
  grafana:
  metabase:
  mysql:
  nextcloud:
  pgadmin:
  postgres:
  redisinsight:
