version: '3.9'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    # restart: always
  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    # restart: always
  mautic:
    image: mautic/mautic
    ports:
      - 8080:80
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: root
      MAUTIC_DB_PASSWORD: password
      MAUTIC_DB_NAME: mautic
      MAUTIC_RUN_CRON_JOBS: 'true'
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
    depends_on:
      - mysql
    # restart: always
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mongo/:/home/shared
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
  mysql:
    image: mysql:8
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql-mode=""
    environment:
      MYSQL_DATABASE: tests
      MYSQL_USER: gabrielrufino
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql/:/home/shared
    # restart: always
  nginx:
    image: nginx:1
    ports:
      - "8080:80"
  pgadmin:
    image: dpage/pgadmin4:5
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gabrielrufino.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "16543:80"
    depends_on:
      - postgres
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: gabrielrufino
      PMA_PASSWORD: 12345678
    ports:
      - "80"
    depends_on:
      - mysql
  portainer:
    image: portainer/portainer-ce:2.9.0
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
    # restart: always
  postgres:
    image: postgres:13
    # [Use the image bellow for postgres with ssl]
    # image: fantix/postgres-ssl:13.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/:/home/shared
    # restart: always
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    # restart: always
  promtail:
    image: grafana/promtail:2.3.0
    ports:
      - 9080:9080
    volumes:
      - ./config/promtail/config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml
    # restart: always
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq
      - ./volumes/rabbitmq/log/:/var/log/rabbitmq
  redis:
    image: redis
    ports:
      - 6379:6379
    # restart: always
  rethinkdb:
    image: rethinkdb:2
    ports:
      - "28015:28015"
      - "28016:8080"
    volumes:
      - ./volumes/rethinkdb/:/home/shared
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
        SA_PASSWORD: "password@123"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  strapi:
    image: strapi/strapi:3
    volumes:
      - ./volumes/strapi:/srv/app
    ports:
      - "1337:1337"
  ubuntu:
    image: ubuntu:20.04
    tty: true
    volumes:
      - ./volumes/ubuntu/:/home/shared
  verdaccio:
    image: verdaccio/verdaccio:4
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./volumes/verdaccio/storage:/verdaccio/storage"

volumes:
  grafana:
