name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v6
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Smoke
        run: sh ./tests/smoke/main.sh
      - name: Integration
        run: sh ./tests/integration/main.sh

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
