name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Smoke
        run: sh ./tests/smoke/main.sh
      - name: Integration
        run: sh ./tests/integration/main.sh

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
