name: Continuous Integration

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Smoke
        run: sh ./tests/smoke/main.sh
      - name: Integration
        run: sh ./tests/integration/main.sh

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
