name: Validation workflow

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cp ./config/prometheus/prometheus.example.yml ./config/prometheus/prometheus.yml
    - run: docker-compose pull
    - run: docker-compose up -d
    - run: docker-compose down
