name: Validation workflow

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: exit 1
    - name: Smoke
      run: sh ./tests/smoke/main.sh
    - name: Integration
      run: sh ./tests/integration/main.sh
    - name: Send email in case of failure
      if: failure() 
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        to: email@gabrielrufino.com
        from: Github - gabrielrufino/docker-compose.yml
        secure: true
        body: Validation job of ${{github.repository}} has failed!
        ignore_cert: true
        priority: high
